### ISSUE TITLE
Fix the bug with the inability to glue notes

### ISSUE THREAD

**Issue by ghost** [HerpDerpinstine/DDSS.LobbyGuard#4]
Hello, I noticed that recently there was a bug with the fact that who installed the anticheat, he can not glue notes, but only throw them (even if you are not the host of the lobby). Perhaps this problem occurs in the whole lobby
Fix it, please, thank you.
- [ ]  Fix bug related to notes

**Comment by HerpDerpinstine** [comment]
Please retest this with v1.6.1 as I can no longer replicate this issue.
